/**
 * Path construction primitives (task F3).
 *
 * A path is a polyline of `{s, x, y, hx, hy}` samples: world position plus a
 * unit heading, parametrized by cumulative arc length s (chord-accumulated,
 * so car-following at dt = 0.1 s steps along exactly the polyline a car
 * renders on). Segments:
 * - straight: exact axis-aligned arithmetic;
 * - quarter arc: generated by iterative rotation in a local frame. The
 *   rotation step comes from halving the exact quarter turn (0,1) with the
 *   half-angle identities — `sqrt` only, no trig functions (R2 whitelist
 *   hygiene; see vec.ts note);
 * - lateral jog: cubic Hermite lateral blend, whose minimum radius is the
 *   rational a²/(6·|Δ|) — again no transcendental ops.
 */
import { PATH_SAMPLE_STEP_METERS } from './constants';
import { itemAt, vadd, vdot, vlen, vnormalize, vscale } from './vec';
import type { Vec2 } from './vec';

export interface PathSample {
  /** Cumulative arc length from the path start (chord sum). */
  readonly s: number;
  readonly x: number;
  readonly y: number;
  /** Unit heading at the sample. */
  readonly hx: number;
  readonly hy: number;
}

function assertFinite(sample: PathSample): void {
  if (!Number.isFinite(sample.s) || !Number.isFinite(sample.x) || !Number.isFinite(sample.y) ||
      !Number.isFinite(sample.hx) || !Number.isFinite(sample.hy)) {
    throw new Error(`non-finite path sample produced (s=${String(sample.s)})`);
  }
}

/**
 * (cos δ, sin δ) for δ = (π/2) / 2^k, plus the step count 2^k, derived by
 * repeated half-angle from the exact quarter turn (cos, sin) = (0, 1). Only
 * `sqrt` is used; sin stays positive because δ ∈ (0, π/2].
 */
export function quarterStepCosSin(radius: number, stepMeters: number): { c: number; s: number; count: number } {
  let count = 1;
  let halvings = 0;
  while ((radius * Math.PI) / 2 / count > stepMeters) {
    count *= 2;
    halvings += 1;
  }
  let c = 0;
  let s = 1;
  for (let i = 0; i < halvings; i += 1) {
    c = Math.sqrt((1 + c) / 2);
    s = Math.sqrt(1 - c * c);
  }
  return { c, s, count };
}

/**
 * Builds a sampled path. All pushes append samples at ≤ PATH_SAMPLE_STEP
 * spacing; segment endpoints are exact; s accumulates chord distances.
 */
export class PathBuilder {
  private readonly samples: PathSample[] = [];
  private currentX = 0;
  private currentY = 0;
  private currentHx = 1;
  private currentHy = 0;
  private s = 0;
  private started = false;

  /** Start the path at `point` with unit `heading`. */
  start(point: Vec2, heading: Vec2): void {
    if (this.started) throw new Error('path already started');
    this.started = true;
    this.currentX = point.x;
    this.currentY = point.y;
    this.currentHx = heading.x;
    this.currentHy = heading.y;
    const sample: PathSample = { s: 0, x: point.x, y: point.y, hx: heading.x, hy: heading.y };
    assertFinite(sample);
    this.samples.push(sample);
  }

  get lengthMeters(): number {
    return this.s;
  }

  get sampleCount(): number {
    return this.samples.length;
  }

  get lastPoint(): Vec2 {
    return { x: this.currentX, y: this.currentY };
  }

  get lastHeading(): Vec2 {
    return { x: this.currentHx, y: this.currentHy };
  }

  finish(): readonly PathSample[] {
    if (!this.started) throw new Error('path never started');
    return this.samples;
  }

  private advanceTo(x: number, y: number, hx: number, hy: number): void {
    const dx = x - this.currentX;
    const dy = y - this.currentY;
    const ds = Math.sqrt(dx * dx + dy * dy);
    if (ds > 1e-9) {
      this.s += ds;
      const sample: PathSample = { s: this.s, x, y, hx, hy };
      assertFinite(sample);
      this.samples.push(sample);
      this.currentX = x;
      this.currentY = y;
      this.currentHx = hx;
      this.currentHy = hy;
    } else {
      // Coincident join: still adopt the new (exact) heading.
      const last = itemAt(this.samples, this.samples.length - 1);
      this.currentHx = hx;
      this.currentHy = hy;
      if (last.hx !== hx || last.hy !== hy) {
        this.samples[this.samples.length - 1] = { s: last.s, x: last.x, y: last.y, hx, hy };
      }
    }
  }

  /** Straight segment from the current point along the current heading. */
  pushStraight(lengthMeters: number): void {
    if (!(lengthMeters > 0)) return;
    const n = Math.max(1, Math.ceil(lengthMeters / PATH_SAMPLE_STEP_METERS));
    const sx = this.currentX;
    const sy = this.currentY;
    const hx = this.currentHx;
    const hy = this.currentHy;
    for (let k = 1; k <= n; k += 1) {
      const t = k / n;
      this.advanceTo(sx + hx * lengthMeters * t, sy + hy * lengthMeters * t, hx, hy);
    }
  }

  /**
   * Quarter-circle arc turning from the current heading `u` toward the
   * lateral direction `v` (the turn side), radius R, starting exactly at the
   * current point. Local frame: p(φ) = (R sin φ, R(1 − cos φ)),
   * heading(φ) = (cos φ, sin φ); world = P0 + a·u + b·v.
   */
  pushQuarterArc(v: Vec2, radius: number): void {
    if (!(radius > 0)) throw new Error(`arc radius must be > 0, got ${String(radius)}`);
    const u = { x: this.currentHx, y: this.currentHy };
    const p0 = { x: this.currentX, y: this.currentY };
    const { c, s, count } = quarterStepCosSin(radius, PATH_SAMPLE_STEP_METERS);
    // Local position/heading, rotated iteratively by δ.
    let ax = 0;
    let ay = 0;
    let hx = 1;
    let hy = 0;
    for (let k = 1; k <= count; k += 1) {
      const rx = ax;
      const ry = ay - radius; // p − C, with C_local = (0, R)
      ax = c * rx - s * ry;
      ay = c * ry + s * rx + radius;
      const nhx = c * hx - s * hy;
      hy = s * hx + c * hy;
      hx = nhx;
      if (k < count) {
        this.advanceTo(
          p0.x + ax * u.x + ay * v.x,
          p0.y + ax * u.y + ay * v.y,
          u.x * hx + v.x * hy,
          u.y * hx + v.y * hy,
        );
      }
    }
    // Land the endpoint and heading exactly (avoids rotation drift at joins).
    this.advanceTo(p0.x + radius * u.x + radius * v.x, p0.y + radius * u.y + radius * v.y, v.x, v.y);
  }

  /**
   * Lateral jog: blend `delta` meters sideways (along +v) over `span` meters
   * ahead (along +u = current heading) using a cubic Hermite lateral profile
   * b(t) = Δ·(3t² − 2t³) — tangent-continuous with the straights on both
   * ends. Minimum radius = span² / (6·|Δ|) (curvature peaks at the ends).
   */
  pushJog(v: Vec2, spanMeters: number, deltaMeters: number): void {
    if (!(spanMeters > 0)) throw new Error(`jog span must be > 0, got ${String(spanMeters)}`);
    const u = { x: this.currentHx, y: this.currentHy };
    const p0 = { x: this.currentX, y: this.currentY };
    const n = Math.max(8, Math.ceil((spanMeters + Math.abs(deltaMeters)) / PATH_SAMPLE_STEP_METERS));
    for (let k = 1; k <= n; k += 1) {
      const t = k / n;
      const a = spanMeters * t;
      const b = deltaMeters * (3 * t * t - 2 * t * t * t);
      const dbdt = deltaMeters * (6 * t - 6 * t * t);
      const heading = vnormalize({ x: spanMeters, y: dbdt });
      this.advanceTo(
        p0.x + a * u.x + b * v.x,
        p0.y + a * u.y + b * v.y,
        u.x * heading.x + v.x * heading.y,
        u.y * heading.x + v.y * heading.y,
      );
    }
  }
}

/**
 * Interpolated sample at arc length `s` (clamped to the path): binary search
 * the polyline, lerp position and heading. The stepping helper F4's
 * car-following integration consumes.
 */
export function sampleAtS(samples: readonly PathSample[], s: number): PathSample {
  const last = itemAt(samples, samples.length - 1);
  const first = itemAt(samples, 0);
  if (s <= first.s) return first;
  if (s >= last.s) return last;
  let lo = 0;
  let hi = samples.length - 1;
  while (hi - lo > 1) {
    const mid = (lo + hi) >> 1;
    if (itemAt(samples, mid).s <= s) lo = mid;
    else hi = mid;
  }
  const a = itemAt(samples, lo);
  const b = itemAt(samples, hi);
  const span = b.s - a.s;
  const t = span > 1e-12 ? (s - a.s) / span : 0;
  const heading = vnormalize(vlerpH(a, b, t));
  const out: PathSample = {
    s,
    x: a.x + (b.x - a.x) * t,
    y: a.y + (b.y - a.y) * t,
    hx: heading.x,
    hy: heading.y,
  };
  assertFinite(out);
  return out;
}

function vlerpH(a: PathSample, b: PathSample, t: number): Vec2 {
  return { x: a.hx + (b.hx - a.hx) * t, y: a.hy + (b.hy - a.hy) * t };
}

/** Distance between two finite segments (Ericson, Real-Time Collision Detection §5.1.9). */
export function segmentDistance(p1: Vec2, q1: Vec2, p2: Vec2, q2: Vec2): number {
  const d1 = { x: q1.x - p1.x, y: q1.y - p1.y };
  const d2 = { x: q2.x - p2.x, y: q2.y - p2.y };
  const r = { x: p1.x - p2.x, y: p1.y - p2.y };
  const a = vdot(d1, d1);
  const e = vdot(d2, d2);
  const f = vdot(d2, r);
  const EPS = 1e-18;
  let s = 0;
  let t = 0;
  if (a <= EPS && e <= EPS) return vlen(r);
  if (a <= EPS) {
    t = clamp01(f / e);
  } else {
    const c = vdot(d1, r);
    if (e <= EPS) {
      s = clamp01(-c / a);
    } else {
      const b = vdot(d1, d2);
      const denom = a * e - b * b;
      s = denom > EPS ? clamp01((b * f - c * e) / denom) : 0;
      t = (b * s + f) / e;
      if (t < 0) {
        t = 0;
        s = clamp01(-c / a);
      } else if (t > 1) {
        t = 1;
        s = clamp01((b - c) / a);
      }
    }
  }
  const c1 = vadd(p1, vscale(d1, s));
  const c2 = vadd(p2, vscale(d2, t));
  return vlen({ x: c1.x - c2.x, y: c1.y - c2.y });
}

function clamp01(x: number): number {
  return x < 0 ? 0 : x > 1 ? 1 : x;
}
